export const STANDARD_PRESETS = [
  {
    name: '世界の株価',
    stocks: [
      { symbol: '^N225', name: '日経平均(日本)', region: 'アジア' },
      { symbol: '^DJI', name: 'NYダウ(米国)', region: '米国' },
      { symbol: '^GSPC', name: 'S&P 500(米国)', region: '米国' },
      { symbol: '^IXIC', name: 'NASDAQ(米国)', region: '米国' },
      { symbol: '^FTSE', name: 'FTSE 100(イギリス)', region: '欧州' },
      { symbol: '^GDAXI', name: 'DAX(ドイツ)', region: '欧州' },
      { symbol: '^FCHI', name: 'CAC 40(フランス)', region: '欧州' },
      { symbol: 'FTSEMIB.MI', name: 'FTSE MIB(イタリア)', region: '欧州' },
      { symbol: '^SSMI', name: 'SMI(スイス)', region: '欧州' },
      { symbol: '^STOXX50E', name: 'ユーロSTOXX50(欧州)', region: '欧州' },
      { symbol: '^HSI', name: 'ハンセン(香港)', region: 'アジア' },
      { symbol: '000001.SS', name: '上海総合(中国)', region: 'アジア' },
      { symbol: '^KS11', name: 'KOSPI(韓国)', region: 'アジア' },
      { symbol: '^TWII', name: '加権指数(台湾)', region: 'アジア' },
      { symbol: '^BSESN', name: 'SENSEX(インド)', region: 'アジア' },
      { symbol: '^NSEI', name: 'NIFTY 50(インド)', region: 'アジア' },
      { symbol: '^STI', name: 'STI(シンガポール)', region: 'アジア' },
      { symbol: '^KLSE', name: 'KLCI(マレーシア)', region: 'アジア' },
      { symbol: '^SET.BK', name: 'SET(タイ)', region: 'アジア' },
      { symbol: '^JKSE', name: 'ジャカルタ(インドネシア)', region: 'アジア' },
      { symbol: '^AXJO', name: 'ASX 200(オーストラリア)', region: 'アジア' },
      { symbol: '^NZ50', name: 'NZX 50(ニュージーランド)', region: 'アジア' },
      { symbol: '^GSPTSE', name: 'TSX(カナダ)', region: 'その他' },
      { symbol: '^MXX', name: 'IPC(メキシコ)', region: 'その他' },
      { symbol: '^BVSP', name: 'ボベスパ(ブラジル)', region: 'その他' },
      { symbol: 'XU100.IS', name: 'BIST 100(トルコ)', region: 'その他' },
      { symbol: '^TA125.TA', name: 'TA-125(イスラエル)', region: 'その他' },
      { symbol: 'IMOEX.ME', name: 'MOEX(ロシア)', region: 'その他' },
      { symbol: '^J203.JO', name: 'JSE TOP40(南アフリカ)', region: 'その他' },
      { symbol: '^MERV', name: 'メルバル(アルゼンチン)', region: 'その他' },
      { symbol: '^CASE30', name: 'EGX 30(エジプト)', region: 'その他' },
    ],
  },
  {
    name: '主要為替',
    stocks: [
      { symbol: 'USDJPY=X', name: 'ドル/円', region: '為替' },
      { symbol: 'EURJPY=X', name: 'ユーロ/円', region: '為替' },
      { symbol: 'GBPJPY=X', name: 'ポンド/円', region: '為替' },
      { symbol: 'AUDJPY=X', name: '豪ドル/円', region: '為替' },
      { symbol: 'NZDJPY=X', name: 'NZドル/円', region: '為替' },
      { symbol: 'CADJPY=X', name: 'カナダドル/円', region: '為替' },
      { symbol: 'CHFJPY=X', name: 'スイスフラン/円', region: '為替' },
      { symbol: 'TRYJPY=X', name: 'トルコリラ/円', region: '為替' },
      { symbol: 'ZARJPY=X', name: 'ランド/円', region: '為替' },
      { symbol: 'MXNJPY=X', name: 'メキシコペソ/円', region: '為替' },
      { symbol: 'EURUSD=X', name: 'EUR/USD', region: '為替' },
      { symbol: 'GBPUSD=X', name: 'GBP/USD', region: '為替' },
      { symbol: 'USDTRY=X', name: 'USD/TRY', region: '為替' },
      { symbol: 'USDCHF=X', name: 'USD/CHF', region: '為替' },
      { symbol: 'USDCAD=X', name: 'USD/CAD', region: '為替' },
      { symbol: 'DX-Y.NYB', name: 'ドルインデックス', region: '為替' },
    ],
  },
  {
    name: '米国株式',
    stocks: [
      { symbol: 'AAPL', name: 'アップル', region: '米国' },
      { symbol: 'MSFT', name: 'マイクロソフト', region: '米国' },
      { symbol: 'GOOGL', name: 'グーグル', region: '米国' },
      { symbol: 'AMZN', name: 'アマゾン', region: '米国' },
      { symbol: 'META', name: 'メタ', region: '米国' },
      { symbol: 'TSLA', name: 'テスラ', region: '米国' },
      { symbol: 'NVDA', name: 'エヌビディア', region: '米国' },
      { symbol: 'NFLX', name: 'ネットフリックス', region: '米国' },
      { symbol: 'MU', name: 'マイクロン', region: '米国' },
      { symbol: 'AVGO', name: 'ブロードコム', region: '米国' },
      { symbol: 'PLTR', name: 'パランティア', region: '米国' },
      { symbol: 'AMD', name: 'AMD', region: '米国' },
      { symbol: 'ARM', name: 'ARM', region: '米国' },
      { symbol: 'SMCI', name: 'スーパーマイクロ', region: '米国' },
      { symbol: 'COIN', name: 'コインベース', region: '米国' },
      { symbol: 'UBER', name: 'ウーバー', region: '米国' },
    ],
  },
  {
    name: '商品先物',
    stocks: [
      { symbol: 'GC=F', name: '金先物', region: '商品' },
      { symbol: 'SI=F', name: '銀先物', region: '商品' },
      { symbol: 'PL=F', name: 'プラチナ先物', region: '商品' },
      { symbol: 'HG=F', name: '銅先物', region: '商品' },
      { symbol: 'CL=F', name: '原油(WTI)', region: '商品' },
      { symbol: 'BZ=F', name: '原油(ブレント)', region: '商品' },
      { symbol: 'NG=F', name: '天然ガス', region: '商品' },
      { symbol: 'RB=F', name: 'ガソリン', region: '商品' },
      { symbol: 'PA=F', name: 'パラジウム', region: '商品' },
      { symbol: 'ZC=F', name: 'とうもろこし', region: '商品' },
      { symbol: 'ZW=F', name: '小麦', region: '商品' },
      { symbol: 'ZS=F', name: '大豆', region: '商品' },
      { symbol: 'KC=F', name: 'コーヒー', region: '商品' },
      { symbol: 'CC=F', name: 'ココア', region: '商品' },
      { symbol: 'CT=F', name: '綿花', region: '商品' },
      { symbol: 'SB=F', name: '砂糖', region: '商品' },
    ],
  },
  {
    name: 'ETF',
    stocks: [
      { symbol: 'SPY', name: 'S&P500 ETF', region: '米国' },
      { symbol: 'QQQ', name: 'NASDAQ100 ETF', region: '米国' },
      { symbol: 'VOO', name: 'S&P500(VOO)', region: '米国' },
      { symbol: 'VTI', name: '米国全体(VTI)', region: '米国' },
      { symbol: 'VT', name: '全世界(VT)', region: '米国' },
      { symbol: 'ACWI', name: 'オールカントリー', region: '米国' },
      { symbol: 'IWM', name: 'ラッセル2000 ETF', region: '米国' },
      { symbol: 'EEM', name: '新興国 ETF', region: '米国' },
      { symbol: 'EFA', name: '先進国 ETF', region: '米国' },
      { symbol: '1306.T', name: 'TOPIX ETF', region: 'アジア' },
      { symbol: '1570.T', name: '日経レバETF', region: 'アジア' },
      { symbol: '1357.T', name: '日経Wインバ', region: 'アジア' },
      { symbol: '2516.T', name: 'グロース250', region: 'アジア' },
      { symbol: '1482.T', name: '日本国債10年', region: 'アジア' },
      { symbol: 'GLD', name: 'ゴールドETF', region: '米国' },
      { symbol: 'SLV', name: 'シルバーETF', region: '米国' },
    ],
  },
  {
    name: '暗号資産',
    stocks: [
      { symbol: 'BTC-USD', name: 'ビットコイン(USD)', region: '暗号資産' },
      { symbol: 'BTC-JPY', name: 'ビットコイン(円)', region: '暗号資産' },
      { symbol: 'ETH-USD', name: 'イーサリアム', region: '暗号資産' },
      { symbol: 'XRP-USD', name: 'リップル', region: '暗号資産' },
      { symbol: 'SOL-USD', name: 'ソラナ', region: '暗号資産' },
      { symbol: 'ADA-USD', name: 'カルダノ', region: '暗号資産' },
      { symbol: 'DOGE-USD', name: 'ドージコイン', region: '暗号資産' },
      { symbol: 'AVAX-USD', name: 'アバランチ', region: '暗号資産' },
      { symbol: 'DOT-USD', name: 'ポルカドット', region: '暗号資産' },
      { symbol: 'LINK-USD', name: 'チェインリンク', region: '暗号資産' },
      { symbol: 'UNI-USD', name: 'ユニスワップ', region: '暗号資産' },
      { symbol: 'LTC-USD', name: 'ライトコイン', region: '暗号資産' },
      { symbol: 'BCH-USD', name: 'ビットコインキャッシュ', region: '暗号資産' },
      { symbol: 'SHIB-USD', name: '柴犬コイン', region: '暗号資産' },
      { symbol: 'MATIC-USD', name: 'ポリゴン', region: '暗号資産' },
      { symbol: 'ATOM-USD', name: 'コスモス', region: '暗号資産' },
    ],
  },
  {
    name: '債券・金利',
    stocks: [
      { symbol: '^TNX', name: '米10年国債', region: '債券' },
      { symbol: '^FVX', name: '米5年国債', region: '債券' },
      { symbol: '^TYX', name: '米30年国債', region: '債券' },
      { symbol: '^IRX', name: '米13週国債', region: '債券' },
      { symbol: '1482.T', name: '日本国債10年(ETF)', region: '債券' },
      { symbol: 'TLT', name: '米長期国債ETF', region: '債券' },
      { symbol: 'SHY', name: '米短期国債ETF', region: '債券' },
      { symbol: 'IEF', name: '米中期国債ETF', region: '債券' },
    ],
  },
];

export function buildStandardLayout(stocks) {
  return stocks.map((stock, i) => ({
    i: stock.symbol,
    x: (i % 8) * 10,
    y: Math.floor(i / 8) * 10,
    w: 10,
    h: 10,
    minW: 1,
    minH: 1,
  }));
}
